#!/usr/bin/env -S node
/**
 * generate-install - extract skill install commands from .skill-lock.json
 * Usage: node generate-install.ts [--app <app>] [--lock <path>] [--skills-dir <path>]
 *
 * Outputs a shell script to stdout. Redirect to a file:
 *   node generate-install.ts > install-skills.sh
 */

import { readFileSync, readdirSync, existsSync } from "fs";
import { homedir } from "os";

// ─── Args ──────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const flag = (name: string, fallback: string) => {
  const i = args.indexOf(name);
  return i !== -1 ? args[i + 1] : fallback;
};

const LOCK_PATH = flag("--lock", `${homedir()}/.agents/.skill-lock.json`);
const SKILLS_DIR = flag("--skills-dir", `${homedir()}/.claude/skills`);
const APP_FLAGS = flag("--app", "claude-code");

// ─── Load ──────────────────────────────────────────────────────────────────

if (!existsSync(LOCK_PATH)) {
  console.error(`skill-lock not found: ${LOCK_PATH}`);
  process.exit(1);
}

type SkillEntry = {
  source: string;
  sourceType: string;
  sourceUrl: string;
  skillPath: string;
  skillFolderHash?: string;
  installedAt: string;
  updatedAt: string;
};

const lock: { version: number; skills: Record<string, SkillEntry> } =
  JSON.parse(readFileSync(LOCK_PATH, "utf8"));

// ─── Group by source ───────────────────────────────────────────────────────

const bySource = new Map<string, string[]>();
for (const [name, entry] of Object.entries(lock.skills)) {
  if (entry.sourceType !== "github") continue;
  if (!bySource.has(entry.source)) bySource.set(entry.source, []);
  bySource.get(entry.source)!.push(name);
}

// ─── Local-only (in dir, not in lock) ─────────────────────────────────────

const lockNames = new Set(Object.keys(lock.skills));
const localOnly = existsSync(SKILLS_DIR)
  ? readdirSync(SKILLS_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory() && !lockNames.has(d.name))
      .map((d) => d.name)
  : [];

// ─── Emit ──────────────────────────────────────────────────────────────────

const pad = (s: string) => `─── ${s} `;
const hr = (label: string) =>
  `# ${pad(label)}`.padEnd(80, "─");

console.log("#!/usr/bin/env bash");
console.log(
  `# Generated by generate-install.ts from ${LOCK_PATH}`
);
console.log(`# ${new Date().toISOString()}`);
console.log(`# Usage: bash <(node ~/Scripts/generate-install.ts)`);
console.log("");
console.log("set -euo pipefail");
console.log(`APP="-a ${APP_FLAGS} -g -y"`);
console.log("");

for (const [source, skills] of bySource) {
  console.log(hr(source));
  const flags = skills.map((s) => `  --skill ${s}`).join(" \\\n");
  console.log(`pnpm dlx skills add ${source} \\\n${flags} \\\n  $APP`);
  console.log("");
}

if (localOnly.length > 0) {
  console.log(hr("LOCAL ONLY — not in lock, no remote source"));
  for (const name of localOnly) {
    console.log(`# ${name}`);
  }
}
