#!/usr/bin/env bash
# Generated by generate-install.ts from /Users/adrianbrowning/.agents/.skill-lock.json
# 2026-06-18T08:26:37.674Z
# Usage: bash <(node ~/Scripts/generate-install.ts)

set -euo pipefail
APP="-a claude-code -g -y"

# ─── anthropics/skills ────────────────────────────────────────────────────────
pnpm dlx skills add anthropics/skills \
  --skill skill-creator \
  $APP

# ─── vercel-labs/skills ───────────────────────────────────────────────────────
pnpm dlx skills add vercel-labs/skills \
  --skill find-skills \
  $APP

# ─── stevenmays/dotfiles ──────────────────────────────────────────────────────
pnpm dlx skills add stevenmays/dotfiles \
  --skill code-review \
  $APP

# ─── sergiodxa/agent-skills ───────────────────────────────────────────────────
pnpm dlx skills add sergiodxa/agent-skills \
  --skill frontend-accessibility-best-practices \
  --skill frontend-async-best-practices \
  --skill frontend-internationalization-best-practices \
  --skill frontend-js-best-practices \
  --skill frontend-react-best-practices \
  --skill frontend-react-router-best-practices \
  --skill frontend-testing-best-practices \
  --skill owasp-security-check \
  --skill skill-writing-best-practices \
  $APP

# ─── remix-run/agent-skills ───────────────────────────────────────────────────
pnpm dlx skills add remix-run/agent-skills \
  --skill react-router-data-mode \
  --skill react-router-declarative-mode \
  --skill react-router-framework-mode \
  $APP

# ─── adrianbrowning/agent-skills ──────────────────────────────────────────────
pnpm dlx skills add adrianbrowning/agent-skills \
  --skill deep-think \
  --skill jherr-dev-workflow \
  --skill plan-to-tasks \
  --skill tdd-integration \
  --skill typescript-patterns \
  --skill react-router-loader-performance \
  $APP

# ─── prisma/skills ────────────────────────────────────────────────────────────
pnpm dlx skills add prisma/skills \
  --skill prisma-cli \
  --skill prisma-client-api \
  --skill prisma-database-setup \
  --skill prisma-upgrade-v7 \
  $APP

# ─── mattpocock/skills ────────────────────────────────────────────────────────
pnpm dlx skills add mattpocock/skills \
  --skill git-guardrails-claude-code \
  --skill design-an-interface \
  --skill grill-me \
  --skill improve-codebase-architecture \
  --skill prd-to-issues \
  --skill prd-to-plan \
  --skill qa \
  --skill request-refactor-plan \
  --skill tdd \
  --skill triage-issue \
  --skill ubiquitous-language \
  --skill write-a-prd \
  --skill write-a-skill \
  --skill domain-model \
  --skill diagnose \
  --skill caveman \
  --skill grill-with-docs \
  --skill to-issues \
  --skill to-prd \
  --skill triage \
  --skill zoom-out \
  --skill handoff \
  --skill prototype \
  $APP

# ─── mcollina/skills ──────────────────────────────────────────────────────────
pnpm dlx skills add mcollina/skills \
  --skill node-best-practices \
  --skill typescript-magician \
  --skill node \
  $APP

# ─── millionco/react-doctor ───────────────────────────────────────────────────
pnpm dlx skills add millionco/react-doctor \
  --skill react-doctor \
  $APP

# ─── cocoindex-io/cocoindex-code ──────────────────────────────────────────────
pnpm dlx skills add cocoindex-io/cocoindex-code \
  --skill ccc \
  $APP

# ─── TanStack/ai ──────────────────────────────────────────────────────────────
pnpm dlx skills add TanStack/ai \
  --skill ai-code-mode \
  --skill ai-core \
  $APP

# ─── brianlovin/agent-config ──────────────────────────────────────────────────
pnpm dlx skills add brianlovin/agent-config \
  --skill agent-browser \
  --skill reclaude \
  --skill simplify \
  $APP

# ─── dmno-dev/varlock ─────────────────────────────────────────────────────────
pnpm dlx skills add dmno-dev/varlock \
  --skill varlock \
  $APP

# ─── AnthonyPAlicea/skills ────────────────────────────────────────────────────
pnpm dlx skills add AnthonyPAlicea/skills \
  --skill do-i-understand \
  $APP

# ─── alejandrobailo/no-use-effect ─────────────────────────────────────────────
pnpm dlx skills add alejandrobailo/no-use-effect \
  --skill no-use-effect \
  $APP

# ─── Cst2989/react-tips-skill ─────────────────────────────────────────────────
pnpm dlx skills add Cst2989/react-tips-skill \
  --skill no-unnecessary-effects \
  --skill react-tips \
  $APP

# ─── vercel-labs/agent-skills ─────────────────────────────────────────────────
pnpm dlx skills add vercel-labs/agent-skills \
  --skill vercel-react-best-practices \
  $APP

# ─── anivar/zod-skill ─────────────────────────────────────────────────────────
pnpm dlx skills add anivar/zod-skill \
  --skill zod \
  $APP

# ─── DietrichGebert/ponytail ──────────────────────────────────────────────────
pnpm dlx skills add DietrichGebert/ponytail \
  --skill ponytail \
  $APP
